### ISSUE TITLE
[Feature] Add support for getting port numbers as arguments instead of hard coding them

### ISSUE THREAD

**Issue by SpyrosRoum** [SpyrosRoum/termpad#1]
I'm not sure if this should happen.
Pro:
    - More customizable and power to the user
Cons:
    - You have to know the port for each self hosted server if you want to use it (Is this really an issue though?)
    - If a client is written one day, you will have to set the ports to be used somehow (arguments/config file/env variables)

**Comment by TheCatster** [comment]
This could be done off of environment variables, possibly in a .env.

**Comment by SpyrosRoum** [comment]
You are correct but it doesn't matter at the moment. 
I am in the process of re-writing the project and once that's done there will be only one port which you will be able to configure with env variables.

I'm leaving this open until the re-write is done but that should be later today
