### ISSUE TITLE
termpad.com has broken IPv6

### ISSUE THREAD

**Issue by Mynacol** [SpyrosRoum/termpad#11]
Hi, I noticed termpad.com has a AAAA DNS record, but I'm unable to connect via this address. Some clients also try IPv4 thanks to Happy Eyeballs, but others may break with this broken setup.

I poked around and it seems the address `2a01:4f9:c010:eb8b::1` does work just fine, but in DNS you have set `2a01:4f9:c010:eb8b::`, which fails. This seems to be a quick fix by changing the resource record.

**Comment by SpyrosRoum** [comment]
Hey thanks for pointing it out, it should be fixed now!
